version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"            # <-- frontend React
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/backend"             # <-- backend Python
    schedule:
      interval: "weekly"
